#!/usr/bin/env python3
"""Cross-language conformance check for earthnet-protocol vectors.

Proves that Python's deterministic Protobuf encoding matches Rust/prost's, so a
signature produced by the Rust core verifies in Python (and vice versa).

For each vector:
  1. decode `wire_hex` into the message
  2. assert the carried signature matches `signature_hex`
  3. clear the signature, re-serialize deterministically
  4. assert it equals `proto_canonical_hex`            <-- the canonicalization cross-check
  5. verify Ed25519 over (domain || canonical) with `pubkey_hex`

Run: python python/verify_vectors.py
Requires: protobuf, cryptography ; earthnet_pb2.py (generated by protoc).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import earthnet_pb2  # noqa: E402

from cryptography.exceptions import InvalidSignature  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey  # noqa: E402

VECTORS = Path(__file__).parent.parent / "tests" / "vectors" / "v0_1.json"

# Maps vector name -> protobuf message class.
MESSAGES = {
    "observation": earthnet_pb2.Observation,
    "confirmed_event": earthnet_pb2.ConfirmedEvent,
}


def check(vec: dict) -> None:
    name = vec["name"]
    cls = MESSAGES[name]
    domain = vec["domain"].encode("ascii")
    pubkey = bytes.fromhex(vec["pubkey_hex"])
    signature = bytes.fromhex(vec["signature_hex"])
    expected_canonical = bytes.fromhex(vec["proto_canonical_hex"])
    wire = bytes.fromhex(vec["wire_hex"])

    msg = cls()
    msg.ParseFromString(wire)

    assert msg.signature == signature, f"{name}: signature field mismatch vs wire"

    msg.ClearField("signature")
    canonical = msg.SerializeToString(deterministic=True)
    assert canonical == expected_canonical, (
        f"{name}: deterministic encoding differs from Rust/prost\n"
        f"  python: {canonical.hex()}\n"
        f"  rust:   {expected_canonical.hex()}"
    )

    Ed25519PublicKey.from_public_bytes(pubkey).verify(signature, domain + canonical)
    print(f"  OK  {name}: canonical bytes match prost; Ed25519 verifies")


def main() -> int:
    data = json.loads(VECTORS.read_text())
    print(f"earthnet-protocol cross-lang vectors v{data['version']} ({len(data['vectors'])} vectors)")
    failures = 0
    for vec in data["vectors"]:
        try:
            check(vec)
        except (AssertionError, InvalidSignature) as e:
            failures += 1
            print(f"  FAIL {vec.get('name')}: {e}")
    if failures:
        print(f"{failures} vector(s) FAILED")
        return 1
    print("all vectors passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
